language: ruby
rvm: 2.3.1
branches:
  only:
  - master
  - develop
services:
  - postgresql
addons:
  postgresql: '9.4'
before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
