version: '2'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - postgres
    env_file: .env
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=pug-api
      - POSTGRES_PASSWORD=pug-api
