version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  web:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - postgres
    env_file: .env
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=pug-api
      - POSTGRES_PASSWORD=pug-api
